import type { NextPage } from 'next'
import Head from 'next/head'

import FeaturesBlocks from '$components/Blocks/Features'
import Testimonials from '$components/Testimonials'
import Newsletter from '@/src/components/Newsletter'
import HeroHome from '@/src/components/Hero/Home'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HeroHome />
      <FeaturesBlocks />
      <Testimonials />
      <Newsletter />
    </>
  )
}

export default Home
